version: 0.2

env:
  parameter-store:
    STACKHAWK_NPM_AUTH_TOKEN: /raptor/npmjs/token-rw
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - mkdir -p dist
      - npm install
  build:
    commands:
      - npm run ci
  post_build:
    commands:
      - ./scripts/package.sh
