name: NaiveAsync Build
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'VERSION'
      - 'README.md'
  pull_request:
    branches:
      - main
jobs:

  build-project:
    runs-on: biodome-arm64
    steps:
      ### Biodome setup
      - name: Biodome job setup
        uses: ./../../../../home/runner/.github/actions/biodome-setup-v2
      - name: Resolve cache
        run: biodome ci restore-cache
      - name: Biodome CI Commands
        run: biodome ci save-secrets
      ### Build steps
      - name: Install Dependencies
        run: npm install
      - name: Run tests
        run: npm run ci
      - name: Persist cache
        if: always()
        run: biodome ci persist-cache
